### PR TITLE
Remove listeners for Touch events in Range Slider

### LINKED ISSUE #346: Range Slider not working on Mobile
For some reason, once you move a range slider, the touch events won't work anymore.

### PR DESCRIPTION
**Pull request by jesusbotella**
Fix #346.

The `touchstart` and `touchend` event listeners were not being properly removed, hence we were moving all thumbs 🤦‍♂️ .

I updated slider event to make it work in mobile. We were not getting touch event position properly.

### CODE REVIEW

File: packages/components/src/components/as-range-slider/MouseTrack.ts [hunk 1]
```diff
@@ -22,7 +22,11 @@ export class MouseTrack {
 
   private _handleRelease(eventProperties: MouseEvent, listeners: MouseListeners, customListeners: MouseListeners) {
     document.removeEventListener('mousemove', listeners.move);
+    document.removeEventListener('touchmove', listeners.move);
     document.removeEventListener('mouseup', listeners.release);
+    document.removeEventListener('touchend', listeners.release);
+
+    document.removeEventListener('dragstart', this.preventAndStop);
```
Comment (IagoLast) [inline packages/components/src/components/as-range-slider/MouseTrack.ts]: why this listener is not in the listeners object?

Comment (jesusbotella) [reply packages/components/src/components/as-range-slider/MouseTrack.ts]: Because we don't have any custom references coming from components. It is always added with the same function reference.

File: packages/components/src/components/as-range-slider/track/as-range-slider-bar.tsx [hunk 2]
```diff
@@ -135,7 +135,15 @@ export class RangeSliderBar extends MouseTrack {
   }
 
   private _getMovementDelta(currentEvent: MouseEvent, previousEvent: MouseEvent) {
```
Comment (IagoLast) [inline packages/components/src/components/as-range-slider/track/as-range-slider-bar.tsx]:
```ts
private _getMovementDelta(currentEvent: MouseEvent|TouchEvent, previousEvent: MouseEvent|TouchEvent) {
```
