### PR TITLE
Fix Range Slider bugs

### LINKED ISSUE #312: Range slider jumps unexpectedly when moving thumb
When using range slider inside a "complex" layout with a left toolbar, it jumps to another position when starting to move the thumb.

airship-slider-bug

### LINKED ISSUE #315: Range slider does not allow decimals
### Context

Setting a slider for opacity like this:

```
            <as-range-slider
              id="opacity-slider"
              min-value="0"
              max-value="1"
              step="0.1"
              value="0.5"></as-range-slider>
```

### Result

opacity

### Expected result
Values are rounded depending on the min and max value. In this case, we should see `0.1 0.2 0.3 ...`

### PR DESCRIPTION
**Pull request by jesusbotella**
This PR fix #315 and fix #312.

Range slider thumb position was being calculated with rail's offsetLeft, and it was not calculated properly when any of the parent elements had any `position: relative`, like `.as-main`. So, this PR uses left offset from `.getBoundingClientRect` which is relative to `document` origin.

Apart from that, we didn't allow decimal numbers in slider's step, and now we do! 🎉

### CODE REVIEW

File: packages/components/src/components/as-range-slider/slider/as-range-slider.tsx [hunk 1]
```diff
@@ -302,6 +302,27 @@ export class RangeSlider {
...
+    const stepValue = (value / this.step) * this.step;
+    return this.roundToStep(stepValue, this.step);
   }
+
+  private roundToStep(numberToRound: number, step: number) {
+    return Number.parseFloat(numberToRound.toFixed(getDecimalPlaces(step)));
+  }
+}
+
+function getDecimalPlaces(decimalNumber): number {
```
Comment (IagoLast) [inline packages/components/src/components/as-range-slider/slider/as-range-slider.tsx]: why outside the class?

Comment (jesusbotella) [reply packages/components/src/components/as-range-slider/slider/as-range-slider.tsx]: I thought It didn't belong to that specific class, but I should've put it in utilities! 😥
